name: hydrosmart
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  infinite_scroll_pagination: ^4.0.0
  path: ^1.9.0
  flutter_bloc: ^8.1.6
  sqflite: ^2.4.0
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.4.1
  url_launcher: ^6.2.2
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

